# Use Node v16 as the base image.
FROM node:16

# Define working directory
WORKDIR /usr/client

# Copy the dependencies & install production dependencies
COPY package.json ./

COPY package-lock.json ./

RUN cd /usr/client; \
    npm ci

# Copy everything in the current directory to our image, in the 'usr/server' folder.
COPY . .

# Build production build 
RUN npm run build --production

RUN npm install -g serve

# Uses port which is used by the actual application
EXPOSE 3000

# Run application
CMD serve -s build